--Crear Temporal y Cargar Datos
CREATE TABLE IF NOT EXISTS Tabla_Temporal(
    ID_DATOS INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_VICTIMA VARCHAR(100),
    APELLIDO_VICTIMA VARCHAR(100),
    DIRECCION_VICTIMA VARCHAR(100),
    FECHA_PRIMERA_SOSPECHA VARCHAR(100),
    FECHA_CONFIRMACION VARCHAR(100),
    FECHA_MUERTE VARCHAR(100),
    ESTADO_VICTIMA VARCHAR(100),
    NOMBRE_ASOCIADO VARCHAR(100),
    APELLIDO_ASOCIADO VARCHAR(100),
    FECHA_CONOCIO VARCHAR(100),
    CONTACTO_FISICO VARCHAR(100),
    FECHA_INICIO_CONTACTO VARCHAR(100),
    FECHA_FIN_CONTACTO VARCHAR(100),
    NOMBRE_HOSPITAL VARCHAR(100),
    DIRECCION_HOSPITAL VARCHAR(100),
    UBICACION_VICTIMA VARCHAR(100),
    FECHA_LLEGADA VARCHAR(100),
    FECHA_RETIRO VARCHAR(100),
    TRATAMIENTO VARCHAR(100),
    EFECTIVIDAD VARCHAR(100),
    FECHA_INICIO_TRATAMIENTO VARCHAR(100),
    FECHA_FIN_TRATAMIENTO VARCHAR(100),
    EFECTIVIDAD_EN_VICTIMA VARCHAR(100)
);

-- Crear Modelo--
CREATE TABLE IF NOT EXISTS Direccion ( 
    ID_Direccion INT NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL ,
    PRIMARY KEY (ID_Direccion)
); 

CREATE TABLE IF NOT EXISTS Estado ( 
    ID_Estado INT NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_Estado)
); 

CREATE TABLE IF NOT EXISTS Hospital ( 
    ID_Hospital INT NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL ,
    ID_Direccion INT NOT NULL ,
    PRIMARY KEY (ID_Hospital),
    FOREIGN KEY (ID_Direccion) REFERENCES Direccion (ID_Direccion) ON DELETE CASCADE  
); 

CREATE TABLE IF NOT EXISTS Victima ( 
    ID_Victima INT NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL ,
    Apellido VARCHAR(100) NOT NULL ,
    ID_Direccion INT NOT NULL ,
    Fecha_Registro DATETIME NOT NULL ,
    Fecha_Confirmacion DATETIME NOT NULL ,
    Fecha_Muerte DATETIME NULL ,
    ID_Estado INT NOT NULL ,
    ID_Hospital INT NULL ,
    PRIMARY KEY (ID_Victima),
    FOREIGN KEY (ID_Direccion) REFERENCES Direccion (ID_Direccion) ON DELETE CASCADE,
    FOREIGN KEY (ID_Estado) REFERENCES Estado (ID_Estado) ON DELETE CASCADE,
    FOREIGN KEY (ID_Hospital) REFERENCES Hospital (ID_Hospital) ON DELETE CASCADE
); 

CREATE TABLE IF NOT EXISTS Asociado ( 
    ID_Asociado INT NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL ,
    Apellido VARCHAR(100) NOT NULL ,
    PRIMARY KEY (ID_Asociado)
); 

CREATE TABLE IF NOT EXISTS Conocio ( 
    ID_Conocio INT NOT NULL AUTO_INCREMENT,
    ID_Victima INT NOT NULL ,
    ID_Asociado INT NOT NULL ,
    Fecha_Conocio DATETIME NULL ,
    PRIMARY KEY (ID_Conocio),
    FOREIGN KEY (ID_Victima) REFERENCES Victima (ID_Victima) ON DELETE CASCADE,
    FOREIGN KEY (ID_Asociado) REFERENCES Asociado (ID_Asociado) ON DELETE CASCADE
); 

CREATE TABLE IF NOT EXISTS TipoContacto ( 
    ID_TipoContacto INT NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL ,
    PRIMARY KEY (ID_TipoContacto)    
); 

CREATE TABLE IF NOT EXISTS Contacto ( 
    ID_Contacto INT NOT NULL AUTO_INCREMENT,
    ID_Victima INT NOT NULL ,
    ID_Asociado INT NOT NULL ,
    ID_TipoContacto INT NULL ,
    Fecha_Inicio_Contacto DATETIME NULL,
    Fecha_Final_Contacto DATETIME NULL ,
    PRIMARY KEY (ID_Contacto),
    FOREIGN KEY (ID_Victima) REFERENCES Victima (ID_Victima) ON DELETE CASCADE,
    FOREIGN KEY (ID_Asociado) REFERENCES Asociado (ID_Asociado) ON DELETE CASCADE,
    FOREIGN KEY (ID_TipoContacto) REFERENCES TipoContacto (ID_TipoContacto) ON DELETE CASCADE
); 

CREATE TABLE IF NOT EXISTS Tratamiento ( 
    ID_Tratamiento INT NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL ,
    Efectividad INT NOT NULL ,
    PRIMARY KEY (ID_Tratamiento)
); 

CREATE TABLE IF NOT EXISTS Detalle_Tratamiento ( 
    ID_DetalleTratamiento INT NOT NULL AUTO_INCREMENT,
    ID_Victima INT NOT NULL ,
    ID_Tratamiento INT NOT NULL ,
    Efectividad_Victima INT NOT NULL ,
    Fecha_Inicio_Tratamiento DATETIME NOT NULL ,
    Fecha_Final_Tratamiento DATETIME NOT NULL ,
    PRIMARY KEY (ID_DetalleTratamiento),
    FOREIGN KEY (ID_Victima) REFERENCES Victima (ID_Victima) ON DELETE CASCADE,
    FOREIGN KEY (ID_Tratamiento) REFERENCES Tratamiento (ID_Tratamiento) ON DELETE CASCADE
); 

CREATE TABLE IF NOT EXISTS Ubicacion ( 
    ID_Ubicacion INT NOT NULL AUTO_INCREMENT,
    ID_Victima INT NOT NULL ,
    ID_Direccion INT NOT NULL ,
    Fecha_Llegada DATETIME NULL ,
    Fecha_Salida DATETIME NULL ,
    PRIMARY KEY (ID_Ubicacion),
    FOREIGN KEY (ID_Victima) REFERENCES Victima (ID_Victima) ON DELETE CASCADE,
    FOREIGN KEY (ID_Direccion) REFERENCES Direccion (ID_Direccion) ON DELETE CASCADE
); 
