LOAD DATA 
INFILE '/var/lib/mysql-files/GRAND_VIRUS_EPICENTER.csv' INTO TABLE Tabla_Temporal
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
NOMBRE_VICTIMA,
APELLIDO_VICTIMA,
DIRECCION_VICTIMA,
FECHA_PRIMERA_SOSPECHA,
FECHA_CONFIRMACION,
FECHA_MUERTE,
ESTADO_VICTIMA,
NOMBRE_ASOCIADO,
APELLIDO_ASOCIADO,
FECHA_CONOCIO,
CONTACTO_FISICO,
FECHA_INICIO_CONTACTO,
FECHA_FIN_CONTACTO,
NOMBRE_HOSPITAL,
DIRECCION_HOSPITAL,
UBICACION_VICTIMA,
FECHA_LLEGADA,
FECHA_RETIRO,
TRATAMIENTO,
EFECTIVIDAD,
FECHA_INICIO_TRATAMIENTO,
FECHA_FIN_TRATAMIENTO,
EFECTIVIDAD_EN_VICTIMA);

-- Cargar al Modelo 

-- Tabla Estado --
INSERT INTO Estado(Nombre)
    SELECT DISTINCT(ESTADO_VICTIMA) FROM Tabla_Temporal WHERE ESTADO_VICTIMA !='';

-- Tabla Tratamiento
INSERT INTO Tratamiento(Nombre,Efectividad)
    SELECT DISTINCT TRATAMIENTO,CONVERT(EFECTIVIDAD,UNSIGNED INTEGER) FROM Tabla_Temporal WHERE TRATAMIENTO !='';

-- Tabla TipoContacto

INSERT INTO TipoContacto(Nombre)
   SELECT DISTINCT(CONTACTO_FISICO) FROM Tabla_Temporal WHERE CONTACTO_FISICO !='';

-- Asociado
INSERT INTO Asociado(Nombre,Apellido)
SELECT DISTINCT NOMBRE_ASOCIADO,APELLIDO_ASOCIADO FROM Tabla_Temporal WHERE NOMBRE_ASOCIADO !='' ;


-- Tabla Direccion
    INSERT INTO Direccion(Nombre)
        SELECT DISTINCT(DIRECCION_VICTIMA) FROM Tabla_Temporal WHERE DIRECCION_VICTIMA !='' AND 
       NOT EXISTS (SELECT Nombre FROM Direccion WHERE Nombre= DIRECCION_VICTIMA);
    
    INSERT INTO Direccion(Nombre)
        SELECT DISTINCT(UBICACION_VICTIMA) FROM Tabla_Temporal WHERE UBICACION_VICTIMA !=''AND 
        NOT EXISTS (SELECT Nombre FROM Direccion WHERE Nombre= UBICACION_VICTIMA);
    
    INSERT INTO Direccion(Nombre)
        SELECT DISTINCT(DIRECCION_HOSPITAL) FROM Tabla_Temporal WHERE DIRECCION_HOSPITAL !='' AND 
        NOT EXISTS (SELECT Nombre FROM Direccion WHERE Nombre= DIRECCION_HOSPITAL);
    

-- Hospital--
INSERT INTO Hospital (Nombre,ID_Direccion)
SELECT DISTINCT NOMBRE_HOSPITAL,Direccion.ID_Direccion AS DIRECCION_HOSPITAL 
FROM Tabla_Temporal 
INNER JOIN Direccion ON Tabla_Temporal.DIRECCION_HOSPITAL = Direccion.Nombre;
-- Victima-------
INSERT INTO Victima(Nombre,Apellido,ID_Direccion,Fecha_Registro,Fecha_Confirmacion,Fecha_Muerte,ID_Estado,ID_Hospital) 
SELECT DISTINCT NOMBRE_VICTIMA,APELLIDO_VICTIMA,Direccion.ID_Direccion AS DIRECCION_VICTIMA,
FECHA_PRIMERA_SOSPECHA,FECHA_CONFIRMACION,
CASE WHEN FECHA_MUERTE = '' THEN NULL 
WHEN FECHA_MUERTE != '' THEN FECHA_MUERTE 
END AS FECHA_MUERTE,
Estado.ID_Estado,
CASE WHEN NOMBRE_HOSPITAL= '' THEN NULL 
WHEN NOMBRE_HOSPITAL!='' THEN Hospital.ID_Hospital 
END AS ID_Hospital 
FROM Tabla_Temporal   
LEFT JOIN Estado ON Tabla_Temporal.ESTADO_VICTIMA = Estado.Nombre 
LEFT JOIN  Hospital ON Tabla_Temporal.NOMBRE_HOSPITAL = Hospital.Nombre 
INNER JOIN Direccion ON Tabla_Temporal.DIRECCION_VICTIMA = Direccion.Nombre;
-- DetalleTratamiento 
INSERT INTO Detalle_Tratamiento(ID_Victima,ID_Tratamiento,Efectividad_Victima,Fecha_Inicio_Tratamiento,Fecha_Final_Tratamiento) 
SELECT  Victima.ID_Victima AS NOMBRE_VICTIMA,Tratamiento.ID_Tratamiento AS TRATAMIENTO,EFECTIVIDAD_EN_VICTIMA,
CASE WHEN FECHA_INICIO_TRATAMIENTO = '' THEN NULL 
WHEN FECHA_INICIO_TRATAMIENTO != '' THEN FECHA_INICIO_TRATAMIENTO 
END AS FECHA_INICIO_TRATAMIENTO,
CASE WHEN FECHA_FIN_TRATAMIENTO = '' THEN NULL 
WHEN FECHA_FIN_TRATAMIENTO != '' THEN FECHA_FIN_TRATAMIENTO 
END AS FECHA_INICIO_TRATAMIENTO FROM Tabla_Temporal  
INNER JOIN Victima ON Tabla_Temporal.NOMBRE_VICTIMA = Victima.Nombre
INNER JOIN Tratamiento ON Tabla_Temporal.Tratamiento = Tratamiento.Nombre ;
-- Ubicacion--  
INSERT INTO Ubicacion(ID_Victima,ID_Direccion,Fecha_Llegada,Fecha_Salida) 
SELECT DISTINCT Victima.ID_Victima AS NOMBRE_VICTIMA,Direccion.ID_Direccion AS UBICACION_VICTIMA,
CASE WHEN FECHA_LLEGADA = '' THEN NULL 
WHEN FECHA_LLEGADA != '' THEN FECHA_LLEGADA 
END AS FECHA_LLEGADA,
CASE WHEN FECHA_RETIRO = '' THEN NULL 
WHEN FECHA_RETIRO != '' THEN FECHA_RETIRO 
END AS FECHA_RETIRO
FROM Tabla_Temporal  
INNER JOIN Victima ON Tabla_Temporal.NOMBRE_VICTIMA = Victima.Nombre 
INNER JOIN Direccion ON Tabla_Temporal.UBICACION_VICTIMA = Direccion.Nombre;

-- Contacto--
INSERT INTO Contacto(ID_Victima,ID_Asociado,ID_TipoContacto,Fecha_Inicio_Contacto,Fecha_Final_Contacto) 
SELECT DISTINCT Victima.ID_Victima AS NOMBRE_VICTIMA,Asociado.ID_Asociado AS NOMBRE_ASOCIADO, 
CASE WHEN CONTACTO_FISICO= '' THEN NULL 
WHEN CONTACTO_FISICO!='' THEN TipoContacto.ID_TipoContacto 
END AS ID_TipoContacto,
CASE WHEN Tabla_Temporal.FECHA_INICIO_CONTACTO = '' THEN NULL 
WHEN Tabla_Temporal.FECHA_INICIO_CONTACTO != '' THEN Tabla_Temporal.FECHA_INICIO_CONTACTO
END AS FECHA_INICIO_CONTACTO,
CASE WHEN FECHA_FIN_CONTACTO = '' THEN NULL 
WHEN FECHA_FIN_CONTACTO != '' THEN FECHA_FIN_CONTACTO
END AS FECHA_FIN_CONTACTO
FROM Tabla_Temporal  
INNER JOIN Victima ON Tabla_Temporal.NOMBRE_VICTIMA = Victima.Nombre 
INNER JOIN Asociado ON Tabla_Temporal.NOMBRE_ASOCIADO = Asociado.Nombre 
INNER JOIN TipoContacto ON Tabla_Temporal.CONTACTO_FISICO = TipoContacto.Nombre ;
-- Conocio--
INSERT INTO Conocio(ID_Victima, ID_Asociado, Fecha_Conocio)
SELECT DISTINCT Victima.ID_Victima, Asociado.ID_Asociado,FECHA_CONOCIO FROM Tabla_Temporal
INNER JOIN Victima ON Tabla_Temporal.NOMBRE_VICTIMA = Victima.Nombre
INNER JOIN Asociado ON Tabla_Temporal.NOMBRE_ASOCIADO = Asociado.Nombre;